- name: configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: Disable default NodeJS server
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enable NodeJS server
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install NodeJS server
    ansible.builtin.dnf:
      name: nodejs
      state: latest

  - name: create expense user
    ansible.builtin.user:
      name: expense

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: Unzip backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes

  - name: Install npm dependencies
    community.general.npm:
      #name: dependecies
      path: /app/npm install

  # - name: Install npm dependencies
  #   community.general.npm: npm install
  #   args: 
  #     chdir: /app

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service

  

  
